# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vin_decoder
spring.datasource.username=postgres
spring.datasource.password=ghjuhju55
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# DaData API settings
dadata.api.url=https://cleaner.dadata.ru/api/v1/clean/vehicle
dadata.api.key=f8b9499abb1cba198dae8071ce40ca0bd030d739
dadata.secret.key=14b4013e9fcaf8d81c26928b084d561292ceeaa3

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE